language: go

go:
  - 1.11
  - tip

go_import_path: github.com/turbonomic/kubeturbo

before_install:
  - go get -v github.com/mattn/goveralls

matrix:
  allow_failures:
    - go: tip

script:
  - make fmtcheck 
  - make vet
  - make product
  - if [ "$TRAVIS_GO_VERSION" == "tip" ] ; then make test ; else $HOME/gopath/bin/goveralls -v -race -service=travis-ci ; fi
