apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo-gke
  labels:
    name: kubeturbo
spec:
  containers:
  - name: kubeturbo-60
    image: vmturbo/kubeturbo:6.0 
    imagePullPolicy: Always
    args:
      - --turboconfig=/etc/kubeturbo/config
      - --v=3
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    secret: 
      secretName: vmt-config  
  restartPolicy: Always
