apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  containers:
  - name: kubeturbo
    #   change version
    image: vmturbo/kubeturbo:6.0
    args:
      - --v=2
#     change kubeconfig path; for K8s 1.6+, kubeconfig parameter can be omitted.
      - --kubeconfig=/etc/kubernetes/kubeconfig
      - --turboconfig=/etc/kubeturbo/config
    volumeMounts:
    - name: turbo-config
      mountPath: /etc/kubeturbo
      readOnly: true
    - name: kubeconfig-dir
#     change mountPath
      mountPath: /etc/kubernetes
      readOnly: true
  volumes:
  - name: turbo-config
    hostPath:
#     change the path to the dir contains kubeturbo config
      path: /etc/kubeturbo
  - name: kubeconfig-dir
    hostPath:
#     change the path to the dir contains kubeconfig
      path: /etc/kubernetes
  restartPolicy: Always
